In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
crop = pd.read_csv("/content/Crop_recommendation.csv")
crop.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [17]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   N            2200 non-null   int64  
 1   P            2200 non-null   int64  
 2   K            2200 non-null   int64  
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object 
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB


In [5]:
crop.shape

(2200, 8)

In [15]:
crop.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [16]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [18]:
crop.duplicated().sum()

np.int64(0)

In [19]:
crop['label'].value_counts()

label
rice           100
maize          100
chickpea       100
kidneybeans    100
pigeonpeas     100
mothbeans      100
mungbean       100
blackgram      100
lentil         100
pomegranate    100
banana         100
mango          100
grapes         100
watermelon     100
muskmelon      100
apple          100
orange         100
papaya         100
coconut        100
cotton         100
jute           100
coffee         100
Name: count, dtype: int64

In [20]:
crop_dict = {
    'rice':1,
    'maize':2,
    'chickpea':3,
    'kidneybeans':4,
    'pigeonpeas':5,
    'mothbeans':6,
    'mungbean':7,
    'blackgram':8,
    'lentil':9,
    'pomegranate':10,
    'banana':11,
    'mango':12,
    'grapes':13,
    'watermelon':14,
    'muskmelon':15,
    'apple':16,
    'orange':17,
    'papaya':18,
    'coconut':19,
    'cotton':20,
    'jute':21,
    'coffee':22
}
crop['crop_num']= crop['label'].map(crop_dict)

In [21]:
crop

N   P   K  temperature   humidity        ph    rainfall   label  \
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice   
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice   
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice   
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice   
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice   
...   ...  ..  ..          ...        ...       ...         ...     ...   
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee   
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee   
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee   
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee   
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee   

      crop_num  
0            1  
1            1  
2            1  
3            1  
4            1  
...        ...  
2195        22  
2196        22  
2197        22  
2198        22  
2199        22  

[2200 rows x 9 columns]

In [22]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

train test split

In [25]:
X= crop.drop(['crop_num'],axis=1)
y=crop['crop_num']

In [26]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=42)

Scale the features using MinMaxScaler


In [27]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [30]:
pd.DataFrame(X_train)

0         1      2         3         4         5         6
0     0.121429  0.078571  0.045  0.217234  0.908990  0.485322  0.296852
1     0.264286  0.528571  0.070  0.537110  0.642579  0.565941  0.176308
2     0.050000  0.485714  0.100  0.536479  0.570058  0.588352  0.089318
3     0.721429  0.464286  0.215  0.474462  0.708898  0.390017  0.345770
4     0.000000  0.085714  0.125  0.764684  0.393181  0.431452  0.278327
...        ...       ...    ...       ...       ...       ...       ...
1755  0.071429  0.000000  0.000  0.355451  0.899329  0.670741  0.332938
1756  0.771429  0.635714  0.210  0.531809  0.819906  0.448294  0.253244
1757  0.078571  0.221429  0.130  0.547921  0.437603  0.461981  0.287198
1758  0.078571  0.850000  0.995  0.132116  0.767637  0.444205  0.183467
1759  0.228571  0.521429  0.085  0.434583  0.560997  0.544650  0.118796

[1760 rows x 7 columns]

Training Models

In [32]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

# create instances of all models

models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes':GaussianNB(),
    'Support Vector Machine': SVC(),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging':BaggingClassifier(),
    'AdaBoost':AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),

}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"{name} with accuracy : {accuracy_score(y_test,y_pred)}")
    print("Confusion matrix : ", confusion_matrix(y_test,y_pred))
    print("--------------------------------------------------------")

Logistic Regression with accuracy : 0.9181818181818182
Confusion matrix :  [[16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  2 18  0  0  2  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 13  0  0  1  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 17  3  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 23  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0

model selection

In [33]:
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9931818181818182

prdictive Model

In [39]:
def recommendation(N,P,K,temperature,humidity,ph,rainfall):
  features = np.array([[N,P,K,temperature,humidity,ph,rainfall]])
  transformed_features = ms.fit_transform(features)
  prediction = rfc.predict(transformed_features)
  print(prediction)
  return prediction[0]

In [49]:
## new input

N = 80
P = 60
K = 70
temperature = 50.0
humidity = 20.0
ph = 4.5
rainfall = 10.0

predict = recommendation(N,P,K,temperature,humidity,ph,rainfall)
crop_dict = { 1:"rice", 2:"maize",3:"chickpea" ,4:"kidneybeans" ,5:"pigeonpeas",6:"mothbeans" ,
  7:"mungbean" ,8:"blackgram",9:"lentil" ,10:"pomegranate" ,11:"banana" ,12:"mango" ,13:"grapes",
   14:"watermelon",15:"muskmelon",16:"apple",17:"orange",18:"papaya" ,19:"coconut" ,20:"cotton" ,21:"jute",
  22:"coffee"
}

if predict in crop_dict:
  crop = crop_dict[predict]
  print("{} is a best crop to be cultivated".format(crop))
else:
  print("unable to  recommend crop for suited environment ")

[4]
kidneybeans is a best crop to be cultivated
